---
apiVersion: v1
kind: Service
metadata:
  name: auth-backend
  labels:
    app: auth-backend
  namespace: manage
spec:
  ports:
    - port: 9096
      targetPort: 9096
  selector:
    app: authority-platform
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: authority-platform
  name: authority-platform
  namespace: manage
spec:
  rules:
    - host: sz-bdy-auth.xxxxx.cn
      http:
        paths:
          - backend:
              serviceName: auth-backend
              servicePort: 9096
            path: /
---
apiVersion: v1
data:
  app.conf: |
    appname = auth
    httpport = 9096
    runmode = prod
    CopyRequestBody = true

    sessionon = true
    ;sessionprovider = redis_sentinel
    ;sessionproviderconfig = 127.0.0.1:26379,100,,4,master

    org_domain = "xxxxx.com"

    ;ldap_host = ad01.xxxxx.cn
    ;ldap_user = "cn=support,ou=xxxxx,dc=xxxxx,dc=cn"
    ;ldap_password = "xxxxx.2018"
    ;ldap_base = "dc=xxxxx,dc=cn"
    ;ldap_mailPostfix = "@xxxxx.com"

    cookie_secret = "7497caa5ab90262d577ff923ea127404"
    special_users = "admin:JDJhJDEwJHNYOFhhOEwycjZnNlJBLnEvMUg5RC5jSVE3SWpUT3Z6MUJoZXF2THZLUkI2ZkxlaDZWc1dX:管理员"
    db_sso = auth:sz_auth_1q2w3e4r5t@tcp(mysql57.rdsmfovgtc87gxt.rds.su.baidubce.com)/auth?parseTime=true&loc=
kind: ConfigMap
metadata:
  name: authority-platform-config
  namespace: manage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authority-platform
  namespace: manage
  labels:
    app: authority-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authority-platform
  template:
    metadata:
      labels:
        app: authority-platform
    spec:
      nodeSelector:
        manage: true
      volumes:
        - name: authority-platform-config
          configMap:
            name: authority-platform-config
            items:
              - key: app.conf
                path: app.conf
      containers:
        - name: auth-backend
          image: harbor.xxxxx.cn/platform/auth:1.0.3
          imagePullPolicy: Always
          command: ["./auth"]
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 2
              memory: 2Gi
          volumeMounts:
            - name: authority-platform-config
              mountPath: /go/src/code.xxxxx.cn/platform/auth/conf/app.conf
          livenessProbe:
            httpGet:
              path: /echo
              port: 9096
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 5
