---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
data:
  redis-config: |
    port 6379
    timeout 0
    loglevel warning
    logfile stdout
    databases 16
    save 900 1
    save 300 10
    save 60 10000
    rdbcompression yes
    dbfilename dump.rdb
    requirepass xxxxx_ac_session
    appendonly yes
    appendfilename appendonly.aof
    appendfsync no
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    slowlog-log-slower-than 10000
    slowlog-max-len 1024
    maxclients 1000000
    maxmemory 3072mb
    maxmemory-policy noeviction
kind: ConfigMap
metadata:
  name: ac-redis-master-config
  namespace: redis
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-volume
  namespace: redis
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: redis
  name: ac-redis-master-local-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-volume
  local:
    path: /data/redis/ac-master
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: manage
              operator: In
              values:
                - true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: redis
  name: ac-redis-master-local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-volume
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ac-redis-master
  name: ac-redis-master
  namespace: redis
spec:
  containers:
  - name: redis
    image: redis:5.0.4
    command:
      - redis-server
      - "/redis-master/redis.conf"
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: 2
        memory: 3072Mi
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: ac-redis-master-local-pvc
    - name: config
      configMap:
        name: ac-redis-master-config
        items:
        - key: redis-config
          path: redis.conf

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ac-redis-master
  name: ac-redis-service
  namespace: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    app: ac-redis-master
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ac-redis-master
  name:  ac-redis-external-service
  namespace: redis
spec:
  type: NodePort
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
      nodePort: 32739
  selector:
    app: ac-redis-master
